spring.application.name=taskflow

server.port=8080

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# PostgreSQL
spring.datasource.url=${TASKFLOW_DB_URL}
spring.datasource.username=${TASKFLOW_DB_USERNAME}
spring.datasource.password=${TASKFLOW_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

github.client-id=${GITHUB_CLIENT_ID}
github.client-secret=${GITHUB_CLIENT_SECRET}
github.redirect-uri=${GITHUB_REDIRECT_URI}